[project]
name = "master-dissertation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "annotated-types>=0.7.0",
    "dotenv>=0.9.9",
    "matplotlib>=3.11.0",
    "ollama>=0.6.2",
    "pandas>=3.0.3",
    "pytest>=9.1.1",
    "pyyaml>=6.0.3",
]
